"""add_raw_text_score_breakdown_rename_file_path

Revision ID: 765cca160f4d
Revises: 0c274d20a1e7
Create Date: 2026-05-27 14:04:50.920249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '765cca160f4d'
down_revision: Union[str, None] = '0c274d20a1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    op.drop_column('resumes', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'raw_text')
    op.drop_column('resumes', 'file_path')
    op.drop_column('analyses', 'score_breakdown')
    # ### end Alembic commands ###
